# Generated by Django 5.2.1 on 2025-06-03 04:27

import core.models
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to=core.models.note_file_path, validators=[core.utils.validate_file]),
        ),
    ]
